Test, Docker compose set up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,21 +1,32 @@
-version: 2.1
-
-orbs:
-  python: circleci/python@0.2.1
-
+version: 2
 jobs:
-  build-and-test:
-    executor: python/default
-    steps:
-      - checkout
-      - python/load-cache
-      - python/install-deps
-      - python/save-cache
-      - run:
-          command: ./manage.py test
-          name: Test
+  build:
+    image: ubuntu-2004:202010-01
+  steps:
+    - checkout
+    - run:
+        name: Install Test Requirments
+        command: pip3 install -r requirements.txt
 
-workflows:
-  main:
-    jobs:
-      - build-and-test
+    - run:
+        name: Start the agent and wait for the registration to end
+        command: |
+          set -x
+          docker-compose up -d
+          trap 'kill $(jobs -p)' EXIT
+          attempt_counter=0
+          max_attempts=45
+          mkdir -p build/reports/agent
+          docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
+          until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
+            if [ ${attempt_counter} -eq ${max_attempts} ]; then
+              echo "Agent failed to register. Terminating..."
+              exit 1
+            fi
+            attempt_counter=$(($attempt_counter+1))
+            sleep 1
+          done
+
+    - run:
+        name: Run Test
+        command: pytest
